package:
  name: codebooks
  version: 0.0.1

source:
  git_url: https://github.com/mhowison/codebooks
  git_tag: v0.0.1

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - htmlmin
    - pandas
    - seaborn
  run:
    - python
    - setuptools
    - htmlmin
    - pandas
    - seaborn

test:
  commands:
    - codebooks -h

about:
  home: https://github.com/mhowison/codebooks
  summary: "Automatic generation of codebooks from dataframes"
  license: BSD
  license_file: LICENSE
