package:
  name: jellyfish
  version: 0.7.1

source:
  git_url: https://github.com/jamesturk/jellyfish
  git_tag: 0.7.1

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - jellyfish

about:
  home: http://github.com/jamesturk/jellyfish
  summary: a library for doing approximate and phonetic matching of strings
  license: BSD License
  license_file: LICENSE

