package:
  name: usaddress
  version: 0.5.10

source:
  fn: usaddress-0.5.10.tar.gz
  url: https://pypi.python.org/packages/89/59/6ae17a9718fdbf43e19f6d7ab89f0916cae489ccd766d1505d2ad802c4d6/usaddress-0.5.10.tar.gz
  md5: 27965f4884050ec610301055958fe509

requirements:
  build:
    - python
    - setuptools
    - python-crfsuite
    - probableparsing
  run:
    - python
    - setuptools
    - python-crfsuite
    - probableparsing

test:
  imports:
    - usaddress

about:
  home: https://github.com/datamade/usaddress
  summary: Parse US addresses using conditional random fields
  license: MIT License
  license_file: LICENSE
