package:
  name: cx_oracle
  version: 7.1.3

source:
  git_url: https://github.com/oracle/python-cx_Oracle
  git_tag: 7.1.3

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - cx_Oracle

about:
  home: https://github.com/oracle/python-cx_Oracle
  summary: Python interface to Oracle Database
  license: BSD 
  license_file: LICENSE.txt
