package:
  name: encfs
  version: 1.9.5

source:
  git_url: https://github.com/vgough/encfs/
  git_tag: v1.9.5

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - gettext
    - openssl
  run:
    - gettext
    - openssl

test:
  commands:
    - encfs --version

about:
  home: http://vgough.github.io/encfs/
  summary: "EncFS: an Encrypted Filesystem for FUSE"
  license: LGPL
  license_file: COPYING
