package:
  name: probableparsing
  version: 0.0.1

source:
  url: https://pypi.python.org/packages/8b/26/5a86ac418ee4cecb127a4a6f98d6b202216b5ac4f6b519328ae81d07ba9e/probableparsing-0.0.1.tar.gz
  md5: 960a1fab176276070111f1f9b2080cca

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - probableparsing

about:
  home: https://github.com/datamade/probableparsing
  summary: Common methods for propbable parsers
  license: MIT License
  license_file: LICENSE
