package:
  name: tmux
  version: 2.8

source:
  git_url: https://github.com/tmux/tmux
  git_tag: 2.8

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
  host:
    - libevent
    - ncurses
  run:
    - libevent
    - ncurses

test:
  commands:
    # Check that no server is running.
    - $(tmux info || true) 2> >(grep "no server running on")

about:
  home: https://tmux.github.io/
  summary: A terminal multiplexer
  license: ISC
  license_file: COPYING
