package:
  name: sirad
  version: 0.2.0

source:
  git_url: https://github.com/ripl-org/sirad
  git_tag: v0.2.0

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - openpyxl
    - pandas
    - pyyaml
  run:
    - python
    - setuptools
    - openpyxl
    - pandas
    - pyyaml

test:
  commands:
    - sirad -v

about:
  home: https://github.com/ripl-org/sirad
  summary: "Secure Infrastructure for Research with Administrative Data"
  license: MIT-like
  license_file: LICENSE.txt
