package:
  name: nlopt
  version: 2.4.2

source:
  url: http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  md5: d0b8f139a4acf29b76dbae69ade8ac54

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - nlopt

about:
  home: http://ab-initio.mit.edu/nlopt
  summary: nonlinear optimization library
  license: LGPL
  license_file: COPYING
