package:
  name: scons
  version: 3.1.1

source:
  url: https://files.pythonhosted.org/packages/ca/46/eb308cb150de5e0e76ad0c87a2449dbc0c75b8662b6eb65b8d0e5506ebc7/scons-3.1.1.tar.gz
  sha256: fd44f8f2a4562e7e5bc8c63c82b01e469e8115805a3e9c2923ee54cdcd6678b3

build:
  # scons has a custom setup.py script, --standard-lib is a custom option
  script: python setup.py install --standard-lib

requirements:
  build:
    - python
    - libxml2
    - lxml
  run:
    - python

test:
  imports:
    - SCons
  commands:
    - scons --help

about:
  home: http://www.scons.org/
  license: MIT
  license_file: README.txt
  summary: Open Source next-generation build tool.
